name: Deploy to WP Engine production environment
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: headlessdb
          # Deploy Options
          REMOTE_PATH: "wp-content/"
          FLAGS: -azvr --inplace --delete --include-from config/include.txt --exclude=".*" --exclude-from config/exclude.txt
          PHP_LINT: TRUE
          SCRIPT: wp-content/config/post-deploy.sh

      # Remove default plugins and themes
      - run: rm wp-content/plugins/hello.php
      - run: rm -rf wp-content/plugins/akismet
      - run: rm -rf wp-content/plugins/genesis-blocks
      - run: rm -rf wp-content/themes/twentynineteen
      - run: rm -rf wp-content/themes/twentytwenty
      - run: rm -rf wp-content/themes/twentytwentyone
      - run: rm -rf wp-content/themes/twentytwentytwo
      - run: rm -rf wp-content/themes/genesis-block-theme
