name: Deploy to WP Engine staging environment
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: zamiokulkasstg
          # Deploy Options
          REMOTE_PATH: "wp-content/"
          FLAGS: -azvr --inplace --delete --include-from config/include.txt --exclude=".*" --exclude-from config/exclude.txt
          PHP_LINT: FALSE
          SCRIPT: wp-content/config/post-deploy.sh

        # Build plugins/acf-alma-mapbox
      - name: Deploy theme assets
        working-directory: themes/zamiokulkas
        run: composer install --no-dev

        # Build plugins/acf-alma-mapbox
      - name: Run Yarn
        working-directory: themes/zamiokulkas
        run: yarn
