name: Deploy to WP Engine production environment
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Action Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }}
          WPE_ENV: zamiokulkasstg
          # Deploy Options
          REMOTE_PATH: "wp-content/"
          FLAGS: -azvr --inplace --delete --include-from config/include.txt --exclude=".*" --exclude-from config/exclude.txt
          PHP_LINT: TRUE
          SCRIPT: wp-content/config/post-deploy.sh

      - name: Install Composer dependencies
        uses: php-actions/composer@v6

      - name: Install Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"

      - name: Install Node.js dependencies
        run: yarn install
